# Generated by Django 4.0.2 on 2023-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=100)),
                ('endingpoint', models.CharField(max_length=100)),
                ('fair', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
        ),
    ]
