# Generated by Django 4.0.2 on 2023-02-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0004_alter_point_latitude_alter_point_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='endingpoint',
            new_name='ending_point',
        ),
    ]
