# Generated by Django 4.0.2 on 2023-02-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_counter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
