# Generated by Django 4.0.2 on 2023-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuser_assigned_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='route_name',
            field=models.CharField(default='short_rpute', max_length=20),
            preserve_default=False,
        ),
    ]
