# Generated by Django 4.0.2 on 2023-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_remove_ticket_route_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='ShortRouteTicket',
        ),
        migrations.RemoveIndex(
            model_name='shortrouteticket',
            name='Ticket_tick_date_9430a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='shortrouteticket',
            name='Ticket_tick_booked__3cd09d_idx',
        ),
        migrations.AddIndex(
            model_name='shortrouteticket',
            index=models.Index(fields=['date'], name='Ticket_shor_date_f1071c_idx'),
        ),
        migrations.AddIndex(
            model_name='shortrouteticket',
            index=models.Index(fields=['booked_by', 'date'], name='Ticket_shor_booked__b82dc2_idx'),
        ),
    ]
